version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  commands:
    - mamba install --file requirements.txt --channel conda-forge
    - mamba install --file docs/requirements.txt --channel conda-forge
    - pip install --no-deps .
    - sphinx-build -M html docs/source _readthedocs/ -W
