name: pytest

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pytest:
    strategy:
      matrix:
        os:
          - label: Linux
            runner: ubuntu-latest
        deps:
          - label: Latest
            spec: ""
          - label: Minimum
            spec: |
              isce3=0.6
              numpy=1.21
              python=3.8
              rasterio=1.2
              scipy=1.5
      fail-fast: false
    name: ${{ matrix.os.label }} • ${{matrix.deps.label }}
    runs-on: ${{ matrix.os.runner }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: requirements.txt
          environment-name: tophu
          extra-specs: ${{ matrix.deps.spec }}
          channels: conda-forge
      - name: Install
        run: |
          pip install --no-deps .
      - name: Test
        run: |
          micromamba install -f test/requirements.txt -c conda-forge
          pytest --cov-report=xml
      - name: Coverage report
        uses: codecov/codecov-action@v2
